---
- name: create config directory
  become: yes
  become_user: '{{ username }}'
  file:
    path: '~{{ username }}/.atom'
    state: directory
    owner: '{{ username }}'
    mode: 'u=rwx,go='
  with_items: "{{ users | map(attribute='username') | list }}"
  loop_control:
    loop_var: username

- name: write config
  become: yes
  become_user: '{{ user.username }}'
  template:
    src: config.cson.j2
    dest: '~{{ user.username }}/.atom/config.cson'
    force: '{{ user.atom_config_overwrite | default(False) }}'
    backup: '{{ user.atom_config_overwrite | default(False) }}'
    owner: '{{ user.username }}'
    mode: 'u=rw,go='
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
  when: "user.atom_config is defined and user.atom_config not in ({}, '', None, omit)"
