---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-atom-ubuntu-min
    image: ubuntu:16.04
  - name: ansible-role-atom-ubuntu-max
    image: ubuntu:18.04

provisioner:
  name: ansible

verifier:
  name: testinfra
